var express = require('express')
var router = express.Router()
const {authController} = require('../controllers')
var upload = require('../helpers/multer')

router.get('/login', authController.login)
router.post('/register', authController.register)
router.get('/getdata', authController.getData)
router.post('/listproduct', authController.addProduct)
router.get('/getproduct', authController.getProduct)
router.patch('/updateproduct', authController.updateProduct)
router.get('/getproductdetail', authController.getProductDetail)
router.post('/postaddtocarts', authController.postAddToCarts)
router.get('/getdatacarts', authController.getDataCarts)
router.post('/deletecartsproduct', authController.deleteCartsProduct)
router.get('/searchproduct', authController.searchProduct)
router.post('/inputtrans', authController.inputSubs)
router.post('/uploadimage', upload.single('browse_file'), authController.inputSubs)
router.get('/gettahun1', authController.getTahun1)
router.get('/gettahun2', authController.getTahun2)
router.get('/gettahun3', authController.getTahun3)

module.exports = router